### ISSUE TITLE
Add a .travis.yml

### ISSUE THREAD

**Issue by imduffy15** [lmars/packer-post-processor-vagrant-s3#42]
It would be neat to see you making use of travisci for PRs and binary building.

Something like the following would work:

```
sudo: false
language: go
go:
- 1.7
script:
- go get github.com/mitchellh/gox
- gox -arch="amd64" -os="windows linux darwin" -output "dist/{{.OS}}-{{.Arch}}/{{.Dir}}" .
- zip -j packer-post-processor-vagrant-s3-windows-amd64-${TRAVIS_TAG}.zip ./dist/windows-amd64/*
- tar -cvzf packer-post-processor-vagrant-s3-linux-amd64-${TRAVIS_TAG}.tar.gz -C dist/linux-amd64/ .
- tar -cvzf packer-post-processor-vagrant-s3-darwin-amd64-${TRAVIS_TAG}.tar.gz -C dist/darwin-amd64/ .
deploy:
  provider: releases
  api_key:
    secure: <REMOVED>
  file: 
    - packer-post-processor-vagrant-s3-windows-amd64-${TRAVIS_TAG}.zip
    - packer-post-processor-vagrant-s3-linux-amd64-${TRAVIS_TAG}.tar.gz
    - packer-post-processor-vagrant-s3-darwin-amd64-${TRAVIS_TAG}.tar.gz 
  on:
    tags: true
    repo: lmars/packer-post-processor-vagrant-s3
```

Use `travis setup releases` to configure the API key accordingly.
